import person from '../images/person.png'

const persons = [
    {
        id:1,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'availble'
    },
    {
        id:2,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'availble'
    },
    {
        id:3,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'mission'
    },
    {
        id:4,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'mission'
    },
    {
        id:5,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'out'
    },
    {
        id:6,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'out'
    },
    {
        id:17,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'availble'
    },
    {
        id:8,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'mission'
    },
    {
        id:9,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'out'
    },
    {
        id:10,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'mission'
    },
    {
        id:11,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'availble'
    },
    {
        id:12,
        userImg:person,
        location:'medea',
        matricule:'123456',
        etat:'out'
    },
]

export default persons